# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftWeChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftWeChat

pod 'RongCloudIM', '~> 2.8.9'
pod 'KxMenu'
pod 'PopMenu'
pod 'JSAnimatedImagesView'
 
end
